import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Your NFT Collections</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>Your Nft Collections</span>
        </h1>

        <p className={styles.description}>
          Here you can Create mint, trade and manage NFTs across 288 EVM Compatible Blockchains.{' '}
          <code className={styles.code}>Directly using apis</code>
        </p>

        <section className={styles.aboutSec}>
          <h1>
            About this Blockchain application
          </h1>
          <ul>
            <li>
              We are generating Thentic API Key and then Users can use that key. (we are storing that API key in local storage so that we can show api after refeshing the page)
            </li>
            <li>

              After generating api key users can create there own nft Collection By using Thentic API
            </li>
            <li>

              After creating nft contracts, users can mint nfts in every contracts
            </li>
            <li>
              Also there is a page in website where you can see all your Minted nfts
            </li>
            <li>
              Users can also trasfer nfts
            </li>
          </ul>

          <p>
            This is website to mint, trade and manage NFTs across 288 Ethereum Virtual Machine Compatible Blockchains using Thentic REST API methods. You can create and embed blockchain transactions to your web applications via Transaction URL or Transaction Pixel.
          </p>

        </section>


        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>
    </div>
  )
}
